export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/wallet";
export * from "@/pages/dashboard/wallet2";
export * from "@/pages/dashboard/trade";
export * from "@/pages/dashboard/deposit";
export * from "@/pages/dashboard/withdraw";